import "@/styles/globals.css";

import { type Metadata } from "next";
import { Figtree, Geist, Geist_Mono } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { Toaster } from "sonner";
import { NuqsAdapter } from 'nuqs/adapters/next/app'

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const figtree = Figtree({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
  
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${figtree.variable}`}>
      <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <TRPCReactProvider>
          <NuqsAdapter>
            {children}
            <Toaster /> 
          </NuqsAdapter>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
